
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async startTranscription() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_transcription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopTranscription() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_transcription") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List usable input devices, excluding loopback/virtual endpoints. The first
 * entry the UI shows is "Default"; these are the named alternatives.
 */
async listInputDevices() : Promise<InputDeviceInfo[]> {
    return await TAURI_INVOKE("list_input_devices");
},
/**
 * Choose an input device by name. Pass `None` (or omit) to follow the OS
 * default. Takes effect on the next recording — the current one is unaffected.
 */
async setInputDevice(name: string | null) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_input_device", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startDictation() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_dictation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseDictation() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_dictation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeDictation() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_dictation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async commitDictation() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_dictation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getUsageStats() : Promise<Result<UsageStatsResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_usage_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscripts(page: PageQuery) : Promise<Result<TranscriptResponse[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcripts", { page }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchTranscripts(query: string, page: PageQuery) : Promise<Result<TranscriptResponse[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_transcripts", { query, page }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportTranscripts() : Promise<Result<TranscriptResponse[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_transcripts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDictionary() : Promise<Result<DictionaryResponse[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dictionary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteTranscript(id: number) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_transcript", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The upsert keys on `term`, so a rename inserts a new row; `previous_term`
 * names the old one to drop, or it lingers and keeps rewriting dictation.
 */
async updateDictionary(term: string, replacement: string, previousTerm: string | null) : Promise<Result<DictionaryResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dictionary", { term, replacement, previousTerm }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteDictionaryEntry(id: number) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_dictionary_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async typeText(text: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("type_text", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Linux-only; the clipboard platforms have nothing to configure.
 */
async getInjectionStatus() : Promise<Result<InjectionStatus, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_injection_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerHotkey(hotkey: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_hotkey", { hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unregisterHotkey() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unregister_hotkey") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerDictationHotkey(hotkey: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_dictation_hotkey", { hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unregisterDictationHotkey() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unregister_dictation_hotkey") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async registerDictationCommitHotkey(hotkey: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("register_dictation_commit_hotkey", { hotkey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unregisterDictationCommitHotkey() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unregister_dictation_commit_hotkey") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRegisteredHotkeys() : Promise<Result<RegisteredHotkeys, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_registered_hotkeys") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo() : Promise<Result<ModelInfoResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetch a model by id. Never changes the active model, so a failed or
 * cancelled download can't leave the override pointing at a missing file.
 * Beyond `MAX_CONCURRENT_DOWNLOADS` it waits in `Queued`.
 */
async startModelDownload(id: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_model_download", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every download queued, running, or holding an error, so the UI can rehydrate
 * after a reload without waiting for the next event.
 */
async getActiveDownloads() : Promise<ActiveDownload[]> {
    return await TAURI_INVOKE("get_active_downloads");
},
/**
 * Cancel a queued or running download. A cancel pressed in the last moments of
 * a transfer arrives after the file is published; the download then stands and
 * the caller learns that from `model-download-complete`.
 */
async cancelModelDownload(id: string) : Promise<void> {
    await TAURI_INVOKE("cancel_model_download", { id });
},
/**
 * Set the active model by catalog id. Evicts the cached engine and eagerly
 * warms the newly selected model in the background, so the first transcription
 * after a switch isn't stalled by load.
 */
async setModelOverride(variant: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_model_override", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The picker's list with the active choice marked, `auto` first. Codes come
 * from the loaded model itself; an English-only model reports
 * `supported: false` and no options.
 */
async getLanguageOptions() : Promise<Result<LanguageSettings, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_language_options") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the dictation language. The loaded engine is repointed rather than
 * evicted — language is a per-run option, so a reload would be pure cost.
 */
async setLanguage(code: string | null) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_language", { code }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHardwareProfile() : Promise<Result<HardwareProfileResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hardware_profile") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The catalog with per-model download state, so the picker renders from one
 * source of truth instead of a hardcoded frontend list.
 */
async getModelCatalog() : Promise<CatalogModel[]> {
    return await TAURI_INVOKE("get_model_catalog");
},
/**
 * List all model files currently on disk.
 */
async getDownloadedModels() : Promise<DownloadedModel[]> {
    return await TAURI_INVOKE("get_downloaded_models");
},
/**
 * Delete a downloaded model file by catalog id. Any model may be deleted,
 * including the active one — transcription then surfaces a "no model" error
 * until another is downloaded.
 */
async deleteModel(variant: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFormatConfig() : Promise<Result<FormatConfig, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_format_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFormatConfig(config: FormatConfig) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_format_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate a candidate config (from the provider modal's "Test" button) by
 * sending one trivial formatting request. Does not persist anything.
 */
async testFormatConnection(config: FormatConfig) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_format_connection", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogsFolder() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_logs_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resize the pill window to one of its two shapes, keeping its bottom-centre
 * fixed so the capsule stays put while the card grows above it.
 */
async resizePill(expanded: boolean) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resize_pill", { expanded }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Forward a log record from the webview into the unified backend log file,
 * so frontend errors land in the same structured log as backend events.
 * `level` is one of: error, warn, info, debug, trace (defaults to info).
 */
async logFrontend(level: string, message: string, context: string | null) : Promise<void> {
    await TAURI_INVOKE("log_frontend", { level, message, context });
},
/**
 * Resolves once the database is open. A command, not an event — an event fired
 * before the webview attaches its listener would be missed, wedging startup.
 */
async waitForAppReady() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("wait_for_app_ready") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActiveDownload = { id: string; status: string; progress: number; error: string | null }
export type ApiError = { code: string; message: string }
/**
 * The full catalog, for the model picker.
 */
export type CatalogModel = { id: string; displayName: string; family: string; 
/**
 * Every decode path this model supports (`streaming`, `single-shot`).
 */
pipelines: string[]; defaultPipeline: string; sizeBytes: number; multilingual: boolean; description: string; detail: string; downloaded: boolean; isActive: boolean }
export type DictionaryResponse = { id: number; term: string; replacement: string; hits: number; createdAt: string }
export type DownloadedModel = { variant: string; displayName: string; sizeBytes: number; isActive: boolean }
/**
 * Persisted formatter configuration.
 */
export type FormatConfig = { 
/**
 * Whether the LLM formatting stage runs.
 */
enabled?: boolean; 
/**
 * Preset id of the active provider (`"ollama"`, `"openai"`, …).
 */
provider?: string; 
/**
 * Endpoint details per provider id.
 */
profiles?: Partial<{ [key in string]: Profile }> }
export type HardwareProfileResponse = { gpuName: string; executionProvider: string; vramGb: number; ramGb: number; recommendedModel: string }
export type InjectionStatus = { 
/**
 * `true` where injection needs external tools the user must install.
 */
configurable: boolean; 
/**
 * Human-readable session, e.g. "Wayland (GNOME)". Empty off Linux.
 */
session: string; selected: string | null; 
/**
 * Best first.
 */
tools: InjectionTool[] }
export type InjectionTool = { name: string; available: boolean; preferred: boolean; installHint: string }
/**
 * A selectable microphone. `is_default` marks the OS default; `is_selected`
 * marks the user's saved preference (or the default when none is saved).
 */
export type InputDeviceInfo = { name: string; isDefault: boolean; isSelected: boolean }
export type LanguageOption = { 
/**
 * ISO code, or `auto` for the detect-per-decode sentinel.
 */
code: string; name: string; isSelected: boolean }
export type LanguageSettings = { 
/**
 * Whether the active model handles anything but English.
 */
supported: boolean; 
/**
 * Empty when `supported` is false.
 */
options: LanguageOption[] }
export type ModelInfoResponse = { downloaded: boolean; downloading: boolean; modelName: string }
/**
 * Pagination, cursor and filter args shared by the transcript list and search.
 */
export type PageQuery = { limit: number | null; cursorCreatedAt: string | null; cursorId: number | null; from: string | null; to: string | null; sortAsc: boolean | null }
/**
 * One provider's endpoint details.
 */
export type Profile = { 
/**
 * Base URL up to (not including) `/chat/completions`. Unused by
 * `anthropic`, which pins its own endpoint.
 */
baseUrl?: string; 
/**
 * Model name/id, e.g. `qwen3:0.6b` or `gpt-4o-mini`.
 */
model?: string; 
/**
 * API key. Empty → no `Authorization` header sent (local Ollama default).
 */
apiKey?: string }
export type RegisteredHotkeys = { ptt: string[]; dictation: string[]; dictation_commit: string[] }
export type TranscriptResponse = { id: number; content: string; wordCount: number; durationSeconds: number | null; 
/**
 * App the transcript was dictated into; `None` when it wasn't determined.
 */
targetApp: string | null; createdAt: string }
export type UsageStatsResponse = { totalWords: number; speakingTimeSeconds: number; totalSessions: number; avgPaceWpm: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
